### ISSUE TITLE
child_categories should be fetched

### ISSUE THREAD

**Issue by matreyes** [unformattmh/mercadolibre#2]
If you have:

```
    mel = Mercadolibre::Api.new({ ... })
    mel.get_category("MLC1430").children_categories
```

you get an array of `Mercadolibre::Entity::Category`
But this categories have only name and id (doesn't have settings or children_categories)

Would be nice to have a `fetch` method like `mel.get_category("MLC1430").children_categories.last.fetch` which calls the api and gets all the info of this Category (including his childrens).

I didn't made a pull request because calling the api from the Category entity was a bit strange... 
¿what do you think?

**Comment by matihick** [comment]
I'm sorry for seeing this so late but the idea is to show you the main categories and when you go deeper in a category, you can fetch children categories calling get_category method. This is just a library to connect to meli API, you could build a class embedding this functionality and putting the fetch method there.
Kind regards.
